#!/bin/sh
set -e

# Runtime configuration entrypoint
# Generates /usr/share/nginx/html/runtime-config.js from environment variables

APP_CONFIG_FILE="/usr/share/nginx/html/runtime-config.js"

# JSON-safe escape for string values
json_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\t/\\t/g' -e 's/$/\\n/' | tr -d '\n'
}

# Required variables for production
API_BASE_URL="${API_BASE_URL:-}"
SENTRY_DSN="${SENTRY_DSN:-}"
ENABLE_MOCK="${ENABLE_MOCK:-false}"
ROUTE_MODE="${ROUTE_MODE:-frontend}"
ENVIRONMENT="${ENVIRONMENT:-production}"
RELEASE="${RELEASE:-}"

# Validate required configuration
if [ -z "$API_BASE_URL" ]; then
  echo "ERROR: API_BASE_URL environment variable is required" >&2
  exit 1
fi

# Validate API_BASE_URL is a valid URL
case "$API_BASE_URL" in
  http://*|https://*) ;;
  *)
    echo "ERROR: API_BASE_URL must be a valid URL starting with http:// or https://" >&2
    exit 1
    ;;
esac

# Validate ROUTE_MODE
case "$ROUTE_MODE" in
  frontend|backend) ;;
  *)
    echo "ERROR: ROUTE_MODE must be 'frontend' or 'backend'" >&2
    exit 1
    ;;
esac

# Validate ENABLE_MOCK
case "$ENABLE_MOCK" in
  true|false) ;;
  *)
    echo "ERROR: ENABLE_MOCK must be 'true' or 'false'" >&2
    exit 1
    ;;
esac

# Prevent mock mode in production
if [ "$ENVIRONMENT" = "production" ] && [ "$ENABLE_MOCK" = "true" ]; then
  echo "ERROR: ENABLE_MOCK cannot be true in production environment" >&2
  exit 1
fi

# Generate runtime config
cat > "$APP_CONFIG_FILE" << EOF
// Runtime configuration - generated by container entrypoint
// This file must be loaded before the application entry script
window.__APP_CONFIG__ = {
  apiBaseUrl: "$(json_escape "$API_BASE_URL")",
  sentryDsn: "$(json_escape "$SENTRY_DSN")",
  enableMock: $ENABLE_MOCK,
  routeMode: "$(json_escape "$ROUTE_MODE")",
  environment: "$(json_escape "$ENVIRONMENT")",
  release: "$(json_escape "$RELEASE")"
}
EOF

echo "Runtime configuration generated successfully"
echo "  API_BASE_URL: $API_BASE_URL"
echo "  ENVIRONMENT: $ENVIRONMENT"
echo "  ROUTE_MODE: $ROUTE_MODE"
echo "  ENABLE_MOCK: $ENABLE_MOCK"

# Execute the main command
exec "$@"
